### ISSUE TITLE
SCIP 2.0のPPコマンドに対する応答について

### ISSUE THREAD

**Issue by rsdlab** [sugarsweetrobotics/urglib#2]
urglibのTransport.cppのメンバ関数であるonCmdPPのなかで，SCIP2.0のPPコマンド送信後に受信される情報について，並びが間違っているかと思いましたので，確認です．

現在は
１．最大距離
２．最小距離

となっておりますが，
https://www.hokuyo-aut.jp/02sensor/07scanner/download/pdf/URG_SCIP20.pdf

こちらをみると
１．最小距離
２．最大距離

かとおもいましたが，いかがでしょうか？

**Comment by sugarsweetrobotics** [comment]
更新しました．どうでしょう？


98ac778ec3c122b1da9f5abae736dcc8ba2bf30a
